// Generated by gencpp from file gazebo_video_monitor_msgs/SetCamera.msg
// DO NOT EDIT!


#ifndef GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_SETCAMERA_H
#define GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_SETCAMERA_H

#include <ros/service_traits.h>


#include <gazebo_video_monitor_msgs/SetCameraRequest.h>
#include <gazebo_video_monitor_msgs/SetCameraResponse.h>


namespace gazebo_video_monitor_msgs
{

struct SetCamera
{

typedef SetCameraRequest Request;
typedef SetCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCamera
} // namespace gazebo_video_monitor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::SetCamera > {
  static const char* value()
  {
    return "62faff843444223b685376b7fecc4898";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::SetCamera&) { return value(); }
};

template<>
struct DataType< ::gazebo_video_monitor_msgs::SetCamera > {
  static const char* value()
  {
    return "gazebo_video_monitor_msgs/SetCamera";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::SetCamera&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::SetCameraRequest> should match
// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::SetCamera >
template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::SetCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_video_monitor_msgs::SetCamera >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::SetCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_video_monitor_msgs::SetCameraRequest> should match
// service_traits::DataType< ::gazebo_video_monitor_msgs::SetCamera >
template<>
struct DataType< ::gazebo_video_monitor_msgs::SetCameraRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_video_monitor_msgs::SetCamera >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::SetCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::SetCameraResponse> should match
// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::SetCamera >
template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::SetCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_video_monitor_msgs::SetCamera >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::SetCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_video_monitor_msgs::SetCameraResponse> should match
// service_traits::DataType< ::gazebo_video_monitor_msgs::SetCamera >
template<>
struct DataType< ::gazebo_video_monitor_msgs::SetCameraResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_video_monitor_msgs::SetCamera >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::SetCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_SETCAMERA_H
