// Generated by gencpp from file gazebo_video_monitor_msgs/StartGmcmRecording.msg
// DO NOT EDIT!


#ifndef GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGMCMRECORDING_H
#define GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGMCMRECORDING_H

#include <ros/service_traits.h>


#include <gazebo_video_monitor_msgs/StartGmcmRecordingRequest.h>
#include <gazebo_video_monitor_msgs/StartGmcmRecordingResponse.h>


namespace gazebo_video_monitor_msgs
{

struct StartGmcmRecording
{

typedef StartGmcmRecordingRequest Request;
typedef StartGmcmRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartGmcmRecording
} // namespace gazebo_video_monitor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecording > {
  static const char* value()
  {
    return "176032962ec0f63db7c7bb19a86e7410";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecording&) { return value(); }
};

template<>
struct DataType< ::gazebo_video_monitor_msgs::StartGmcmRecording > {
  static const char* value()
  {
    return "gazebo_video_monitor_msgs/StartGmcmRecording";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecording&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecordingRequest> should match
// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecording >
template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGmcmRecordingRequest> should match
// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGmcmRecording >
template<>
struct DataType< ::gazebo_video_monitor_msgs::StartGmcmRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_video_monitor_msgs::StartGmcmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse> should match
// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecording >
template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse> should match
// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGmcmRecording >
template<>
struct DataType< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_video_monitor_msgs::StartGmcmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGMCMRECORDING_H
