// Generated by gencpp from file gazebo_video_monitor_msgs/StartGvmRecording.msg
// DO NOT EDIT!


#ifndef GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGVMRECORDING_H
#define GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGVMRECORDING_H

#include <ros/service_traits.h>


#include <gazebo_video_monitor_msgs/StartGvmRecordingRequest.h>
#include <gazebo_video_monitor_msgs/StartGvmRecordingResponse.h>


namespace gazebo_video_monitor_msgs
{

struct StartGvmRecording
{

typedef StartGvmRecordingRequest Request;
typedef StartGvmRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartGvmRecording
} // namespace gazebo_video_monitor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecording > {
  static const char* value()
  {
    return "74a62fa060bc26d4ef1f8e73a79a72f6";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGvmRecording&) { return value(); }
};

template<>
struct DataType< ::gazebo_video_monitor_msgs::StartGvmRecording > {
  static const char* value()
  {
    return "gazebo_video_monitor_msgs/StartGvmRecording";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGvmRecording&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecordingRequest> should match
// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecording >
template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGvmRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGvmRecordingRequest> should match
// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGvmRecording >
template<>
struct DataType< ::gazebo_video_monitor_msgs::StartGvmRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_video_monitor_msgs::StartGvmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGvmRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecordingResponse> should match
// service_traits::MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecording >
template<>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_video_monitor_msgs::StartGvmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGvmRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGvmRecordingResponse> should match
// service_traits::DataType< ::gazebo_video_monitor_msgs::StartGvmRecording >
template<>
struct DataType< ::gazebo_video_monitor_msgs::StartGvmRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_video_monitor_msgs::StartGvmRecording >::value();
  }
  static const char* value(const ::gazebo_video_monitor_msgs::StartGvmRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGVMRECORDING_H
