// Generated by gencpp from file gazebo_video_monitor_msgs/StartGmcmRecordingResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGMCMRECORDINGRESPONSE_H
#define GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGMCMRECORDINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_video_monitor_msgs
{
template <class ContainerAllocator>
struct StartGmcmRecordingResponse_
{
  typedef StartGmcmRecordingResponse_<ContainerAllocator> Type;

  StartGmcmRecordingResponse_()
    {
    }
  StartGmcmRecordingResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartGmcmRecordingResponse_

typedef ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<std::allocator<void> > StartGmcmRecordingResponse;

typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse > StartGmcmRecordingResponsePtr;
typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse const> StartGmcmRecordingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gazebo_video_monitor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_video_monitor_msgs/StartGmcmRecordingResponse";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartGmcmRecordingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gazebo_video_monitor_msgs::StartGmcmRecordingResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STARTGMCMRECORDINGRESPONSE_H
