// Generated by gencpp from file gazebo_video_monitor_msgs/StopRecordingRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STOPRECORDINGREQUEST_H
#define GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STOPRECORDINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_video_monitor_msgs
{
template <class ContainerAllocator>
struct StopRecordingRequest_
{
  typedef StopRecordingRequest_<ContainerAllocator> Type;

  StopRecordingRequest_()
    : discard(false)
    , filename()  {
    }
  StopRecordingRequest_(const ContainerAllocator& _alloc)
    : discard(false)
    , filename(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _discard_type;
  _discard_type discard;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopRecordingRequest_

typedef ::gazebo_video_monitor_msgs::StopRecordingRequest_<std::allocator<void> > StopRecordingRequest;

typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingRequest > StopRecordingRequestPtr;
typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingRequest const> StopRecordingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator1> & lhs, const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.discard == rhs.discard &&
    lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator1> & lhs, const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_video_monitor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2996a92a7f8b4bf91dc0b84a5fda46f1";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2996a92a7f8b4bf9ULL;
  static const uint64_t static_value2 = 0x1dc0b84a5fda46f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_video_monitor_msgs/StopRecordingRequest";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool discard     # True to discard the recording\n"
"string filename  # Filename without extension\n"
;
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.discard);
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopRecordingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_video_monitor_msgs::StopRecordingRequest_<ContainerAllocator>& v)
  {
    s << indent << "discard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.discard);
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STOPRECORDINGREQUEST_H
