// Generated by gencpp from file gazebo_video_monitor_msgs/StopRecordingResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STOPRECORDINGRESPONSE_H
#define GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STOPRECORDINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_video_monitor_msgs
{
template <class ContainerAllocator>
struct StopRecordingResponse_
{
  typedef StopRecordingResponse_<ContainerAllocator> Type;

  StopRecordingResponse_()
    : path()
    , success(false)  {
    }
  StopRecordingResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StopRecordingResponse_

typedef ::gazebo_video_monitor_msgs::StopRecordingResponse_<std::allocator<void> > StopRecordingResponse;

typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingResponse > StopRecordingResponsePtr;
typedef boost::shared_ptr< ::gazebo_video_monitor_msgs::StopRecordingResponse const> StopRecordingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator1> & lhs, const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator1> & lhs, const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_video_monitor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33ae47e901cc2aa6ac7b9defcd67a418";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33ae47e901cc2aa6ULL;
  static const uint64_t static_value2 = 0xac7b9defcd67a418ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_video_monitor_msgs/StopRecordingResponse";
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path      # Absolute path to the recording\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopRecordingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_video_monitor_msgs::StopRecordingResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_VIDEO_MONITOR_MSGS_MESSAGE_STOPRECORDINGRESPONSE_H
